---
- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: install the MySQL packages
  yum: 
    name: "{{ mysql_pkgs_list }}" 
    state: installed

- name: Configuring server.cnf [mariadb]
  template: 
    src: server.cnf.j2 
    dest: /etc/my.cnf.d/server.cnf 
    owner: root 
    group: root 
    mode: 0644
  when: ansible_distribution_major_version|int >=7
  notify: restart_mysqld

- name: make sure the service is started
  service: 
    name: "{{ mysql_service_name }}" 
    state: started 
    enabled: true

- name: set mysql root password
  mysql_user: 
    name: root 
    password: "{{ mysql_root_pass }}"
  no_log: True

- name: copy a .my.cnf for future operations
  template: 
    src: my.cnf.j2 
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0640

- name: Ensuring test database is deleted
  mysql_db: 
    name: test 
    state: absent
  
# Backup
- name: Ensuring backup user and jobs
  include_role:
    name: centos-backup
    tasks_from: client

# Zabbix/monitoring
- block:
    - name: Configuring agent in Zabbix server
      include_role:
        name: zabbix-server
        tasks_from: agent_config
      vars:
        zabbix_templates: "{{ zabbix_mysql_templates }}"
        zabbix_groups: "{{ zabbix_mysql_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"  
  tags:
    - monitoring
  when: zabbix_api_srv is defined
